In [1]:
import sys
import os
sys.path.append("../../..")


import numpy as np
from user_settings import *
from CoreAgent import CoreAgent
from ThinkingFlow import ThinkingFlow
from prompts import *


# define energy identify and divide agent
task_evaluating_agent = CoreAgent(template=task_evaluating_prompt_new)
task_dividing_agent = CoreAgent(template=task_dividing_prompt_new)

### task_evaluating_agent

In [2]:
test_task1 = """You will become a researcher on multi-llm agent framework. You need to read paper/code of current state of art framework of multi-llm agents. Ultimately, I want you to be able to 
design and implement your own structure with useful difference compare to the existing structures"""
test_task2= "I want to keep promote my product to customer, I want to know how to do it online and offline"
sub_test_task1 = """Establish a Foundation in Multi-Agent Systems\n- Begin by reading introductory materials on multi-agent systems to understand the basic concepts, terminology, and theoretical underpinnings.
\n- Identify and complete any prerequisite learning, such as courses or tutorials on artificial intelligence, machine learning, and software engineering principles relevant to multi-agent systems."""
sub_test_task2 = """Conduct a Literature Review\n- Search for and compile a list of recent papers and articles on multi-agent systems, specifically focusing on frameworks that utilize language learning models (LLMs).
\n- Organize the literature by themes, such as architecture, communication protocols, learning strategies, and application domains."""

In [3]:
task_evaluating_agent.run(current_task=test_task1)

'Time needed:\n100000 hours\n\nComplexity score:\n100'

In [7]:
task_evaluating_agent.run(current_task=sub_test_task1)

'Time needed:\n200 hours\n\nComplexity score:\n80'

In [8]:
task_evaluating_agent.run(current_task=sub_test_task2)

'Time needed:\n40 hours\n\nComplexity score:\n65'

### task_dividing_agent

In [3]:
task_dividing_agent.run(current_task=test_task2)

"Step1 (initial): Define the product and target audience\n- Identify the unique selling points (USPs) of the product\n- Determine the demographics and psychographics of the target audience\n\nStep2 (following Step1): Set clear marketing objectives\n- Decide what you want to achieve (e.g., brand awareness, sales increase, customer engagement)\n\nStep3 (following Step2): Establish a budget\n- Determine the overall budget for marketing activities\n- Allocate funds for both online and offline strategies\n\nStep4 (following Step3): Develop a marketing plan\n- Outline the strategies and tactics to be used\n- Create a timeline for implementation\n\nStep5 (following Step4): Online marketing strategy development\n- Research the most effective online platforms for your target audience\n\nStep6 (option Step5): Create a website or optimize an existing one\n- Ensure the website is user-friendly and optimized for search engines (SEO)\n- Include clear product information and a call to action (CTA)\n\

### momentum thinking flow


In [3]:
from xyz.magics.agent.MomentumThinkingFlow import MomentumThinkingflow

In [4]:
test_momentum_tf = MomentumThinkingflow()

In [5]:
test_momentum_tf.get_energy(task=test_task1)

array([100000.,    100.])

In [6]:
test_momentum_tf.get_energy(task=sub_test_task1)

array([200.,  80.])

In [5]:
test_momentum_tf.divide_task(task=test_task2)

[('Step1',
  'initial',
  'Define the product and target audience - Identify the unique selling points (USPs) of the product - Determine the demographics and psychographics of the target audience'),
 ('Step2',
  'Step1',
  'Set clear marketing objectives - Decide what you want to achieve (e.g., brand awareness, sales increase, customer engagement)'),
 ('Step3',
  'Step2',
  'Budget planning - Allocate a budget for both online and offline marketing strategies'),
 ('Step4',
  'Step3',
  'Develop a marketing message - Create a compelling message that resonates with your target audience'),
 ('Step5',
  'Step4',
  'Choose online marketing strategies - Option Step5: Social media marketing - Option Step5: Email marketing - Option Step5: Content marketing (blogs, articles, videos) - Option Step5: Search engine optimization (SEO) - Option Step5: Pay-per-click advertising (PPC) - Option Step5: Influencer partnerships'),
 ('Step6',
  'Step5',
  'Choose offline marketing strategies - Option Step6:

In [8]:
test_momentum_tf.divided_tasks_extraction(task_dividing_agent.run(current_task=test_task1))

[{'Step': 'Step 1: Establish a Foundation',
  'Description': '**1.1:** Familiarize yourself with the basics of LLMs and multi-agent systems.\n- **1.2:** Identify and gather foundational papers and resources on LLMs.\n- **1.3:** Read through introductory materials to understand the core concepts and terminology.'},
 {'Step': 'Step 2: Conduct a Literature Review',
  'Description': "**2.1:** Search for recent papers on multi-LLM agent frameworks using academic databases like Google Scholar, arXiv, and IEEE Xplore.\n- **2.2:** Create a document to summarize each paper's key points, contributions, and methodologies.\n- **2.3:** Identify the current state-of-the-art frameworks and their limitations."},
 {'Step': 'Step 3: Deepen Your Understanding',
  'Description': '**3.1:** Select a few state-of-the-art frameworks to study in-depth.\n- **3.2:** Read the selected papers thoroughly and take detailed notes.\n- **3.3:** Reach out to authors or experts if you have questions or need clarification

In [7]:
test_momentum_tf.divided_tasks_extraction(task_dividing_agent.run(current_task=test_task1))

['Step 1: Define the Scope and ObjectivesIdentify the specific area of multi-agent systems you are interested in (e.g., robotics, virtual agents, etc.).\n- Clarify what you mean by "useful difference" and set clear objectives for your research and development.',
 'Step 2: Conduct a Preliminary SurveySearch for recent surveys or review papers on multi-agent systems to get an overview of the field.\n- List down the key terms, concepts, and frameworks mentioned in these surveys.',
 'Step 3: Literature ReviewUse academic databases like Google Scholar, IEEE Xplore, and others to find state-of-the-art papers on multi-agent systems.\n- Read abstracts and conclusions to select relevant papers for detailed study.\n- Organize the papers into categories based on similarities in approaches or applications.',
 'Step 4: Deep Dive into Selected PapersRead the selected papers in detail, focusing on methodology, experiments, and results.\n- Take notes on the strengths and weaknesses of each framework.\

### Test MomentumModule divide task functions

In [8]:
from xyz.magics.momentum.MomentumModule import MomentumModule
from xyz.magics.agent.MomentumThinkingFlow import MomentumThinkingflow

test_momentum_tf = MomentumThinkingflow()
test_task1 = """You will become a researcher on multi-llm agent framework. You need to read paper/code of current state of art framework of multi-llm agents. Ultimately, I want you to be able to 
design and implement your own structure with useful difference compare to the existing structures"""
sub_test_task1 = """Establish a Foundation in Multi-Agent Systems\n- Begin by reading introductory materials on multi-agent systems to understand the basic concepts, terminology, and theoretical underpinnings.
\n- Identify and complete any prerequisite learning, such as courses or tutorials on artificial intelligence, machine learning, and software engineering principles relevant to multi-agent systems."""
sub_test_task2 = """Conduct a Literature Review\n- Search for and compile a list of recent papers and articles on multi-agent systems, specifically focusing on frameworks that utilize language learning models (LLMs).
\n- Organize the literature by themes, such as architecture, communication protocols, learning strategies, and application domains."""

In [9]:
testMomentum = MomentumModule(goal=test_task1, longterm_memory=None, shortterm_memory=None, thinkingflow=test_momentum_tf)

In [10]:
testMomentum.energy

array([1000.,   90.])

In [11]:
decomposed_list = testMomentum.decompose()


retrying, this is 1 time


In [12]:
decomposed_list

In [9]:
import re

# Provided text input
text = """
Step1 (initial): Define the product and target audience
- Identify the unique selling points (USPs) of the product
- Determine the demographics and psychographics of the target audience

Step2 (following Step1): Set clear marketing objectives
- Decide what you want to achieve (e.g., brand awareness, sales increase, customer engagement)

Step3 (following Step2): Establish a budget
- Determine the overall budget for marketing activities
- Allocate funds for both online and offline strategies

Step4 (following Step3): Develop a marketing plan
- Outline the strategies and tactics to be used
- Create a timeline for implementation

Step5 (following Step4): Online marketing strategy development
- Research the most effective online platforms for your target audience

Step6 (option Step5): Create a website or optimize an existing one
- Ensure the website is user-friendly and optimized for search engines (SEO)
- Include clear product information and a call to action (CTA)

Step7 (option Step5): Utilize social media
- Choose the right social media platforms based on your audience
- Plan content and posting schedule

Step8 (option Step5): Implement email marketing
- Build an email list
- Design email campaigns

Step9 (option Step5): Explore online advertising
- Look into pay-per-click (PPC) campaigns, display ads, and social media ads
- Set up tracking for performance analysis

Step10 (following Step4): Offline marketing strategy development
- Identify offline channels that reach your target audience

Step11 (option Step10): Networking and events
- Attend industry events, trade shows, and networking events
- Plan and prepare materials for event promotion

Step12 (option Step10): Traditional advertising
- Consider print, radio, or television ads
- Design ad creatives and select appropriate media outlets

Step13 (option Step10): Direct mail
- Design and send out brochures, flyers, or postcards
- Target specific geographic areas or demographics

Step14 (option Step10): In-store promotions
- Plan in-store events or special promotions
- Create point-of-sale displays or materials

Step15 (following Step4): Execute the marketing plan
- Implement the strategies outlined in the marketing plan
- Monitor progress and adjust tactics as necessary

Step16 (following Step15): Measure and analyze results
- Collect data from both online and offline marketing efforts
- Use analytics tools to measure success against objectives

Step17 (following Step16): Refine and adjust strategies
- Review what worked and what didn't
- Make necessary adjustments to improve future marketing efforts
"""

# Regular expression to match the steps and their descriptions
regex = r"Step(\d+) \((initial|following Step(\d+)|option Step(\d+))\): ([^\n]+)((?:\n- [^\n]+)+)"

# Find all matches in the text
matches = re.findall(regex, text)

# Process matches to format them as required
formatted_steps = []
for match in matches:
    step_number = "Step" + match[0]
    step_reference = match[1]
    if step_reference.startswith('following'):
        step_reference = 'Step' + match[2]
    if  step_reference.startswith('option'):
        step_reference = 'Step' + match[3]
    step_content = match[4] + ' ' + ' '.join(match[5].strip().split('\n'))
    formatted_steps.append((step_number, step_reference, step_content))

# Output the list of tuples
print(formatted_steps)

[('Step1', 'initial', 'Define the product and target audience - Identify the unique selling points (USPs) of the product - Determine the demographics and psychographics of the target audience'), ('Step2', 'Step1', 'Set clear marketing objectives - Decide what you want to achieve (e.g., brand awareness, sales increase, customer engagement)'), ('Step3', 'Step2', 'Establish a budget - Determine the overall budget for marketing activities - Allocate funds for both online and offline strategies'), ('Step4', 'Step3', 'Develop a marketing plan - Outline the strategies and tactics to be used - Create a timeline for implementation'), ('Step5', 'Step4', 'Online marketing strategy development - Research the most effective online platforms for your target audience'), ('Step6', 'Step5', 'Create a website or optimize an existing one - Ensure the website is user-friendly and optimized for search engines (SEO) - Include clear product information and a call to action (CTA)'), ('Step7', 'Step5', 'Utiliz

In [13]:
for ele in decomposed_list:
    print(f"the goal is:{ele.goal}, the energy is {ele.energy}")

the goal is:Step 1: Establish a Foundation**1.1:** Identify key terminology and concepts related to multi-LLM agent frameworks.
- **1.2:** Gather a list of foundational papers and texts on LLMs and multi-agent systems.
- **1.3:** Set up a document or a note-taking system to organize insights and references., the energy is [40. 65.]
the goal is:Step 2: Conduct a Literature Review**2.1:** Read through the foundational texts to understand the basics of LLMs and multi-agent frameworks.
- **2.2:** Search for recent papers on multi-LLM agent frameworks using academic databases like Google Scholar, arXiv, etc.
- **2.3:** Create a literature review document summarizing each paper's objectives, methods, and findings., the energy is [40. 65.]
the goal is:Step 3: Analyze Current State-of-the-Art Frameworks**3.1:** Select a handful of state-of-the-art frameworks to focus on.
- **3.2:** Read the selected papers in-depth and analyze their code if available.
- **3.3:** Identify the strengths and limi

### Consciousness Module

In [2]:
from xyz.magics.consciousness.ConsciousnessModule import ConsciousnessModule


# Example dictionary with id as key and 2D numpy array as value
# the arrays are for dimension time needed, complexity, time to deadline
example_task = {
    "task1": np.array([40, 65, 60]),
    "task2": np.array([30, 75, 35]),
    "task3": np.array([8, 80, 10000]),
}

test_consciousness = ConsciousnessModule(momemtums=example_task)
test_consciousness.sort_momentum()

['task2', 'task1', 'task3']