In [1]:
import sys
import os
sys.path.append("../../..")


import numpy as np
from user_settings import *
from CoreAgent import CoreAgent
from ThinkingFlow import ThinkingFlow
from prompts import task_evaluating_prompt, task_dividing_prompt


# define energy identify and divide agent
task_evaluating_agent = CoreAgent(template=task_evaluating_prompt)
task_dividing_agent = CoreAgent(template=task_dividing_prompt)

### task_evaluating_agent

In [2]:
test_task1 = """You will become a researcher on multi-llm agent framework. You need to read paper/code of current state of art framework of multi-llm agents. Ultimately, I want you to be able to 
design and implement your own structure with useful difference compare to the existing structures"""
sub_test_task1 = """Establish a Foundation in Multi-Agent Systems\n- Begin by reading introductory materials on multi-agent systems to understand the basic concepts, terminology, and theoretical underpinnings.
\n- Identify and complete any prerequisite learning, such as courses or tutorials on artificial intelligence, machine learning, and software engineering principles relevant to multi-agent systems."""
sub_test_task2 = """Conduct a Literature Review\n- Search for and compile a list of recent papers and articles on multi-agent systems, specifically focusing on frameworks that utilize language learning models (LLMs).
\n- Organize the literature by themes, such as architecture, communication protocols, learning strategies, and application domains."""

In [3]:
task_evaluating_agent.run(current_task=test_task1)

'Time needed:\n100000 hours\n\nComplexity score:\n100'

In [7]:
task_evaluating_agent.run(current_task=sub_test_task1)

'Time needed:\n200 hours\n\nComplexity score:\n80'

In [8]:
task_evaluating_agent.run(current_task=sub_test_task2)

'Time needed:\n40 hours\n\nComplexity score:\n65'

### task_dividing_agent

In [4]:
task_dividing_agent.run(current_task=test_task1)

"Certainly! To become a researcher on multi-ILM (Intelligent Learning Models) agent frameworks and to ultimately design and implement a unique structure, we can break down the task into the following steps:\n\n## Step 1: Establish a Foundation\n- **1.1:** Familiarize yourself with the basics of machine learning, artificial intelligence, and multi-agent systems if you haven't already.\n- **1.2:** Identify and gather foundational papers and textbooks on multi-agent systems and machine learning.\n- **1.3:** Review these materials to ensure a solid understanding of the fundamental concepts.\n\n## Step 2: Conduct a Literature Review\n- **2.1:** Search for recent academic papers, articles, and conference proceedings on multi-ILM agent frameworks.\n- **2.2:** Use databases like Google Scholar, arXiv, IEEE Xplore, and others to find relevant literature.\n- **2.3:** Create a document to summarize each paper's key points, contributions, and methodologies.\n\n## Step 3: Deep Dive into Current Sta

### momentum thinking flow


In [3]:
from xyz.magics.agent.MomentumThinkingFlow import MomentumThinkingflow

In [4]:
test_momentum_tf = MomentumThinkingflow()

In [5]:
test_momentum_tf.get_energy(task=test_task1)

array([100000.,    100.])

In [6]:
test_momentum_tf.get_energy(task=sub_test_task1)

array([200.,  80.])

In [8]:
test_momentum_tf.divided_tasks_extraction(task_dividing_agent.run(current_task=test_task1))

[{'Step': 'Step 1: Establish a Foundation',
  'Description': '**1.1:** Familiarize yourself with the basics of LLMs and multi-agent systems.\n- **1.2:** Identify and gather foundational papers and resources on LLMs.\n- **1.3:** Read through introductory materials to understand the core concepts and terminology.'},
 {'Step': 'Step 2: Conduct a Literature Review',
  'Description': "**2.1:** Search for recent papers on multi-LLM agent frameworks using academic databases like Google Scholar, arXiv, and IEEE Xplore.\n- **2.2:** Create a document to summarize each paper's key points, contributions, and methodologies.\n- **2.3:** Identify the current state-of-the-art frameworks and their limitations."},
 {'Step': 'Step 3: Deepen Your Understanding',
  'Description': '**3.1:** Select a few state-of-the-art frameworks to study in-depth.\n- **3.2:** Read the selected papers thoroughly and take detailed notes.\n- **3.3:** Reach out to authors or experts if you have questions or need clarification

In [7]:
test_momentum_tf.divided_tasks_extraction(task_dividing_agent.run(current_task=test_task1))

['Step 1: Define the Scope and ObjectivesIdentify the specific area of multi-agent systems you are interested in (e.g., robotics, virtual agents, etc.).\n- Clarify what you mean by "useful difference" and set clear objectives for your research and development.',
 'Step 2: Conduct a Preliminary SurveySearch for recent surveys or review papers on multi-agent systems to get an overview of the field.\n- List down the key terms, concepts, and frameworks mentioned in these surveys.',
 'Step 3: Literature ReviewUse academic databases like Google Scholar, IEEE Xplore, and others to find state-of-the-art papers on multi-agent systems.\n- Read abstracts and conclusions to select relevant papers for detailed study.\n- Organize the papers into categories based on similarities in approaches or applications.',
 'Step 4: Deep Dive into Selected PapersRead the selected papers in detail, focusing on methodology, experiments, and results.\n- Take notes on the strengths and weaknesses of each framework.\

### Test MomentumModule divide task functions

In [8]:
from xyz.magics.momentum.MomentumModule import MomentumModule
from xyz.magics.agent.MomentumThinkingFlow import MomentumThinkingflow

test_momentum_tf = MomentumThinkingflow()
test_task1 = """You will become a researcher on multi-llm agent framework. You need to read paper/code of current state of art framework of multi-llm agents. Ultimately, I want you to be able to 
design and implement your own structure with useful difference compare to the existing structures"""
sub_test_task1 = """Establish a Foundation in Multi-Agent Systems\n- Begin by reading introductory materials on multi-agent systems to understand the basic concepts, terminology, and theoretical underpinnings.
\n- Identify and complete any prerequisite learning, such as courses or tutorials on artificial intelligence, machine learning, and software engineering principles relevant to multi-agent systems."""
sub_test_task2 = """Conduct a Literature Review\n- Search for and compile a list of recent papers and articles on multi-agent systems, specifically focusing on frameworks that utilize language learning models (LLMs).
\n- Organize the literature by themes, such as architecture, communication protocols, learning strategies, and application domains."""

In [9]:
testMomentum = MomentumModule(goal=test_task1, longterm_memory=None, shortterm_memory=None, thinkingflow=test_momentum_tf)

In [10]:
testMomentum.energy

array([1000.,   90.])

In [11]:
decomposed_list = testMomentum.decompose()


retrying, this is 1 time


In [12]:
decomposed_list

In [13]:
for ele in decomposed_list:
    print(f"the goal is:{ele.goal}, the energy is {ele.energy}")

the goal is:Step 1: Establish a Foundation**1.1:** Identify key terminology and concepts related to multi-LLM agent frameworks.
- **1.2:** Gather a list of foundational papers and texts on LLMs and multi-agent systems.
- **1.3:** Set up a document or a note-taking system to organize insights and references., the energy is [40. 65.]
the goal is:Step 2: Conduct a Literature Review**2.1:** Read through the foundational texts to understand the basics of LLMs and multi-agent frameworks.
- **2.2:** Search for recent papers on multi-LLM agent frameworks using academic databases like Google Scholar, arXiv, etc.
- **2.3:** Create a literature review document summarizing each paper's objectives, methods, and findings., the energy is [40. 65.]
the goal is:Step 3: Analyze Current State-of-the-Art Frameworks**3.1:** Select a handful of state-of-the-art frameworks to focus on.
- **3.2:** Read the selected papers in-depth and analyze their code if available.
- **3.3:** Identify the strengths and limi

### Consciousness Module

In [2]:
from xyz.magics.consciousness.ConsciousnessModule import ConsciousnessModule


# Example dictionary with id as key and 2D numpy array as value
# the arrays are for dimension time needed, complexity, time to deadline
example_task = {
    "task1": np.array([40, 65, 60]),
    "task2": np.array([30, 75, 35]),
    "task3": np.array([8, 80, 10000]),
}

test_consciousness = ConsciousnessModule(momemtums=example_task)
test_consciousness.sort_momentum()

['task2', 'task1', 'task3']